# Generated by Django 4.2.11 on 2024-03-14 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=200)),
                ('incident_type', models.CharField(default='', max_length=50)),
                ('description', models.TextField(default='')),
                ('location', models.CharField(default='', max_length=500)),
                ('images', models.ImageField(default='', upload_to='report_images/')),
                ('videos', models.FileField(default='', upload_to='report_videos/')),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
