# Generated by Django 4.2.9 on 2024-03-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='username',
            field=models.CharField(default='(anonymous)', max_length=150),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='images',
            field=models.ImageField(blank=True, default='', upload_to='report_images/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='report',
            name='videos',
            field=models.FileField(blank=True, default='', upload_to='report_videos/'),
        ),
    ]
