# Generated by Django 4.2.10 on 2024-03-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_report_resolved_report_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
