# Generated by Django 4.2.10 on 2024-03-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0007_alter_report_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="status",
            field=models.CharField(
                choices=[("new", "New"), ("in_progress", "In Progress")],
                default="new",
                max_length=20,
            ),
        ),
    ]
